### ISSUE TITLE
Webhook "not sent yet" when an invoice is paid

### ISSUE THREAD

**Issue by Rednas07** [lnbits/lnbits#1643]
**Describe the bug**
Webhook is not sent after an invoice is paid. From lnbits when clicking on the paid invoice, a blue label is shown with "not sent yet" and this remains the same forever.

I'm using Voltage - LND - lnbits.

**To Reproduce**
1. Get a Voltage node.
2. Open a lnbits instance.
3. Create a lightning invoice through the API and fill in a webhook.
4. Get the invoice paid
5. Click on the invoice, here you will see the blue label showing "not sent yet"

**Expected behavior**
Webhook should be called when the invoice is paid.

**Screenshots**
![image](https://user-images.githubusercontent.com/55803312/233794708-917761aa-7611-448c-8808-42280013b480.png)

**Desktop (please complete the following information):**
 - LNbits version: Commit version: docker
 - LND Version: 0.16.0-beta
 - Voltage Version: v0.3.22

**Additional context**
I know this was an issue that was mentioned earlier. But those are both closed and even though I have the latest version, I still have the problem. (other posts: https://github.com/lnbits/lnbits/issues/924, https://github.com/lnbits/lnbits/issues/487)

**Comment by callebtc** [comment]
Can you check the console whether you see a payment notification once the payment arrives? Question is if the invoice listeners are to blame, or the websocket part.

**Comment by Rednas07** [comment]
Can anyone solve this?

**Comment by callebtc** [comment]
Do you see "> payment notification" in your terminal where you run LNbits?

**Comment by Rednas07** [comment]
> Do you see "> payment notification" in your terminal where you run LNbits and receive a payment?

I can't access the lnbits terminal in a Voltage.cloud node. Is there anyone that can test this?

**Comment by callebtc** [comment]
> I can't access the lnbits terminal in a Voltage.cloud node. Is there anyone that can test this?

I don't know how I should debug this if we can't get access to the logs. The question is: does the invoice listener fail or is it something else. For that we need to have access to the log. 

Can you reproduce the bug in your own instance?

**Comment by Rednas07** [comment]
I cant get my own instance to run, can anyone test this for me? 

Thanks alot.

**Comment by callebtc** [comment]
It works great for me...

**Comment by Rednas07** [comment]
Weird... Then the Voltage instance causes the problem.

**Comment by Rednas07** [comment]
![image](https://user-images.githubusercontent.com/55803312/235305938-80965975-e78b-4223-88dd-cbc085b7abc3.png)

I still get this error. I need this function for my project. How can I fix this?

**Comment by Rednas07** [comment]
![image](https://user-images.githubusercontent.com/55803312/235306006-cf03cf62-e101-4c3a-8cca-e50d48a51892.png)

I still get this error. I need this function for my project, is there any way to fix this?

**Comment by sutt** [comment]
Getting the same behavior on Voltage, Webhook is displaying as "not sent yet" for all successful invoices.

I've tried my listening with my own remote server on Google Cloud, and did not see the request come in. I also tried adding google.com as the webhook url, just to see if it was a cert thing or something, but still displaying "not sent yet"

<img width="380" alt="image" src="https://user-images.githubusercontent.com/2819112/235960844-acf52551-b743-4c7b-a24d-d1639ff499c3.png">

Also, I'm seeing the payment received, with amount going into my wallet, and payment action in the Voltage node's logs:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/2819112/235962433-9fee32ae-fabd-4a9d-885d-2e417ad68514.png">

Is it correct to assume this webhook just generates an HTTP GET and fires it at the url in the webhook?

**Comment by sutt** [comment]
Note for Voltage users, your LNBits will likely be on the version when you first spun up your node. You can check what version you have by grabbing the eight character hash in the dashboard printout below and running `git checkout 11006ef` then `git log` to see when the last commit was. 

<img width="610" alt="image" src="https://user-images.githubusercontent.com/2819112/235964777-1fbdf30e-c9f4-4ee3-9b8d-4fd03db8e062.png">

For me I was on a May 2022 version, and thus need to explicitly update on the Voltage GUI by hitting "update". This should help with this issue https://github.com/lnbits/lnbits/issues/924, fixed August 2022. I'll report back in a few mins if it worked.

**Comment by sutt** [comment]
Yay the update worked, with correct behavior we should at least see google reject our hook with the "405" tag.

@Rednas07 updating LNBits on your voltage dashboard (as shown above) may fix your issue. Especially if you created your voltage server more than a few months ago.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/2819112/235968719-8c654618-d01c-4c3d-a0e3-9e0ecc2f1a29.png">

**Comment by Rednas07** [comment]
@sutt that's great! Thank you. I never saw an update button as you did, but after restarting my node a few times it updated by itself. Happy it works.

**Comment by sutt** [comment]
@Rednas07  Yeah I've found Voltage hosted LNBits to not reliably forward the webhook. 
Meaning the payment does show as completed, and the sats are in the wallet while the webhook shows "not sent yet" on the payment details modal.
The fix appears to be using voltage Dashboard screen to Stop, then Start the LNBits instance. Then you must launch the LNBits instance and "unlock" it via a password. After completing those my webhooks forwarded again.
Couple notes:
 - During development, I'm creating lots of stale invoices, wonder if this is straining on the db or some kind of queue?
 - Looks like voltage has me on commit 26d661d which appears to be a January 2023 release.

**Comment by Rednas07** [comment]
@sutt This indeed works. Thank you a lot for the solution, I really needed that function.

**Comment by gkrizek** [comment]
@sutt and @Rednas07 , the latest version of LNbits on Voltage right now is 0.10.5. Can you please make sure you're on the latest version and see if this is still an issue? Additionally, please message our support and we can look at logs to help debug. Thanks!

**Comment by gkrizek** [comment]
@Rednas07 Ok thanks that's helpful. Can you email me (graham@voltage.cloud) your email or dashboard name and I can look at the logs to try to debug the issue?

Thanks!

**Comment by sutt** [comment]
@gkrizek I'm up to date on 10.6 (95071eb87e94481a0b2e5bcd29517eaa1f8c8dee) and had an initial problem seeing a list of any invoices. They were coming back on the network tab but not loading to the page itself. Turns out `core/static/js/wallet.js` was cached and page needed hard reload which fixed it (see screenshot).

I see in the [fix](https://github.com/lnbits/lnbits/pull/1613/files#diff-4012ea44a039fdab6621fa379bc9e6d55e2e05d049d05af99b14476b75d35f75R3) there was an update to CACHE_VERSION, not sure if that might get overridden on voltage server or if maybe I did something weird in devtools to bring it on myself.

Now that lnbits is updated I'll report back if I see uninitiated webhooks happening again, so far seems like they are working.

<img width="554" alt="image" src="https://github.com/lnbits/lnbits/assets/2819112/0d38c82f-f4d5-4095-9260-54c8ca8d46d0">

**Comment by talvasconcelos** [comment]
Consider closing the issue, if everything is working as expected.

**Comment by sutt** [comment]
@talvasconcelos  The regression where webhook would *never* send (covered in issue https://github.com/lnbits/lnbits/issues/1753) has been preventing me from testing this issue. 

Great to see it's been fixed, as soon as I can get the fix onto my node I'll try testing this. 

Note this issue is a little harder to nail down since it's not totally reproducible, you just have to create roughly a dozen invoices, for it to stop working. So it might take a little time, but I will close or report new behavior soon. Thank you!

**Comment by sutt** [comment]
Tentatively labelling this closed. 

Looks like I've received yvette release and the webhook is forwarding 🎉. LNbits required a restart for this to take place and wondering if this will need consistent restarts as more invoices are generated (?)

@talvasconcelos you can close this issue, but I'm not OP and can't close myself.

**Comment by mattius459** [comment]
Hey all, I'm still having this issue pop up for me with the voltage LNbits. My LNbits version is: 0.11.3

And the version on the voltage side is: v0.2.3_e88e45d

Like @sutt I too am creating some stale invoices so perhaps that is linked, dunno. Either way, the instance seems to work for between 1 hour and 1 day and then when the webhook stops firing I have to stop and start my voltage lnbits instance again.

Have consulted with @gkrizek on this as well and he can't seem to figure it out yet.

**Comment by dni** [comment]
i have noticed that the core task runner is only started once and if it fails its never restarted, i think i fixed it in this pr.

https://github.com/lnbits/lnbits/pull/2290/files#diff-e6e017cf88dd39a8ffe52eafde6f12bdc1bd8cf164a668a084dcb16a95ee925fR486

**Comment by mattius459** [comment]
I'm unfamiliar with how often a merge will happen with lnbits. Do you know when this fix might be applied?

**Comment by sutt** [comment]
Great to hear this is still getting tested + worked on. 
@dni is most likely more fresh with this issue, and thank you for your contributions.
IIRC - this issue did come back for me, despite my indications above that it was fixed; it worked initially then I had to keep restarting to get reliable perf. Then I had to pause lightning dev so I haven't kept up to date....

FYI - when I was looking through the codebase there was a hardcoded 5 (or something small like that) in initializing a `Queue` to handle these callbacks. And when this number got exceeded in outstanding invoices, it would destroy the reliability of getting the callback to fire. I think this is likely to happend more in testing since invoices often have short expiration periods and thus in real life, most apps aren't seeing more than five invoices in this period, but when testing you end up creating a lot of invoices quickly which triggers this bug.  I never got this hypothesis fully replicated and tested, so don't take any of this as definite, just a hunch.

**Comment by dni** [comment]
thanks for the hint of the Queue max i saw that aswell and i thought 5 should be sufficient, because the Queue should be almost instantaneously consumed. i will look into that when the other pr's  are through.

@mattius459 i dont think the invoice expiry should have an impact on that because only successful payments should land in the queue not pending ones.

**Comment by mattius459** [comment]
Thanks guys,

To be clear, my generating of invoices during testing isn't THAT much. Maybe 5-6 per minute max. I'm still generating them with manual clicks (no loops to my knowledge), so if they are nearly instantly consumed my usage should have never broke it.

**Comment by LightRider5** [comment]
I have the same issue with Alby as funding source. Invoices are paid but webhook is never fired. LNbits restart was not helping. From what I see in the terminal the invoice listener is also not notified. With LND as funding source everything worked fine. 
![Screenshot 2024-03-05 at 12 06 37](https://github.com/lnbits/lnbits/assets/48626097/efe9988a-46f6-4152-9e95-26e193937819)

**Comment by bitkarrot** [comment]
I don't think I implemented the webhook for the alby integration. 
It appears there is one for the lntips as wallet, try that and if it works. 

Just don't get mad, some of us, like myself, aren't paid to do all this hard work anyway. 
If you really want it, please implement it yourself :) 

> I have the same issue with Alby as funding source. Invoices are paid but webhook is never fired. LNbits restart was not helping. From what I see in the terminal the invoice listener is also not notified.

**Comment by dni** [comment]
web hooks should now be way more stable. i think this issue should be resolved with next release `0.12.5`

**Comment by mattius459** [comment]
Hey guys, I'm trying to implement the webhook back into my codebase but it still appears to not fire the webhook even though the payment settles. This is actually different than before where it fired about 90% of the time. Now it doesn't seem to fire at all.

<img width="483" alt="Screen Shot 2024-07-19 at 10 22 16 AM" src="https://github.com/user-attachments/assets/36409032-fc9e-4a52-8845-2050d60924a9">
