### ISSUE TITLE
LNURL can now be supported by CLightningWallet without Spark

### ISSUE THREAD

**Issue by gdassori** [lnbits/lnbits#625]
To have a working LNURL on CLD, one must use Spark Backend (which is broken as well in the current version).

This can be changed as in recent versions of CLD the bolt11 description hash option is available.

But the signatures of all clients `create_invoice` [method](https://github.com/lnbits/lnbits-legend/blob/313c40dc2b6517f681504a6fa4e4b0023e287d74/lnbits/wallets/base.py#L58) MUST be changed, from "description_hash" to "description", for **consistency**, because CLD doesn't want the "description_hash" value but the raw "description". 
Indeed, CLD hash the description by itself using a `deschashonly` boolean param since version 0.11 in the invoice RPC method.

At this point, I think a "hash_description()" function utility should be made, to be used in other implementations to pass the description_hash to the wallet backend, like [LND](https://github.com/lnbits/lnbits-legend/blob/313c40dc2b6517f681504a6fa4e4b0023e287d74/lnbits/wallets/lndgrpc.py#L132) and maybe others.

However, this is blocked by an outdated pylightning release on pypi:

https://github.com/ElementsProject/lightning/issues/5265

The current version of pylightning, indeed, doesn't support the `deschashonly` param, required to have it working.

I did the change on my local code and it is working, if there's a design ACK I can try a PR, once the CLD team has released a new version of pylightning.

**Comment by willcl-ark** [comment]
Hey @gdassori I'd be curious to see your changes! I did have a go at making this work myself, including changing the call to invoice (to `ln.call`) so that it returns a description_hash:

```python
    async def create_invoice(
        self,
        amount: int,
        memo: Optional[str] = None,
        description_hash: Optional[bytes] = None,
    ) -> InvoiceResponse:
        label = "lbl{}".format(random.random())
        msat = int(amount * 1000)

        try:
            r = self.ln.call(
                    method='invoice',
                    payload={
                        'msatoshi': msat,
                        'label': label,
                        'description': memo,
                        'exposeprivatechannels': True,
                        'deschashonly': True
                    },
                )
            return InvoiceResponse(True, label, r["bolt11"], "")
        except RpcError as exc:
            error_message = f"lightningd '{exc.method}' failed with '{exc.error}'."
            return InvoiceResponse(False, label, None, error_message)

```

But at this point I am getting a mis-match between the CL-generated description hash and the one LNURL is coming up with and using to verify to payment..

**Comment by talvasconcelos** [comment]
I believe this is fixed already in latest version. Can you close the issue?

**Comment by daywalker90** [comment]
I believe this is not fixed. When i try to pay to a lightning address with lnbits and a cln wallet i get `Payment failed: CLN method 'pay' failed with 'bolt11 uses description_hash, but you did not provide description parameter'.`

**Comment by talvasconcelos** [comment]
Can this be closed?

**Comment by daywalker90** [comment]
no, cln is still planning to move forward with requiring the description in a future version as far as i know

**Comment by motorina0** [comment]
> I believe this is not fixed. When i try to pay to a lightning address with lnbits and a cln wallet i get `Payment failed: CLN method 'pay' failed with 'bolt11 uses description_hash, but you did not provide description parameter'.`
> 
> See [#1553](https://github.com/lnbits/lnbits/issues/1553) for more logs

@dni is this fixed?

**Comment by dni** [comment]
yeah, i think this is solved i use cln with lnurl a lot
